---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo
  labels: 
    component: db  
spec:
  selector:
    matchLabels:
      run: mongo
  replicas: 1
  template:
    metadata:
      labels:
        run: mongo
    spec:
      volumes:
        - name: input-efs
          nfs:
            server: fs-36694db5.efs.us-east-1.amazonaws.com #LDC2019E42-efs
            path: /
        - name: output-efs # Modify for you output setup, example uses NFS
          nfs:
            server: fs-b7bb8534.efs.us-east-1.amazonaws.com #teamgaia-ta1-output
            path: /WORKING/data/db #NOTE: mkdir on efs WORKING/data/db
      containers:
        - name: db
          image: mongo
          ports: 
            - containerPort: 27017
          volumeMounts:
            - name: input-efs
              mountPath: /input
              readOnly: true
            - name: output-efs
              mountPath: /data/db
      nodeSelector:
        eks.amazonaws.com/nodegroup: gaia-eks-nodegroup
---
apiVersion: batch/v1
kind: Job
metadata:
  name: fs-setup
spec:
  template:
    spec:
      volumes:
        - name: input-efs
          nfs:
            server: fs-36694db5.efs.us-east-1.amazonaws.com #LDC2019E42-efs
            path: /
        - name: output-efs
          nfs:
            server: fs-b7bb8534.efs.us-east-1.amazonaws.com #teamgaia-ta1-output
            path: /
      containers:
        # - name: mkdir-aida-edl 
          # image: limanling/uiuc_ie_m18
          # command: ["mkdir", "-p", "/output/system/aida_edl"]
          # volumeMounts:
            # - name: input-efs
              # mountPath: /input
              # readOnly: true
            # - name: output-efs
              # mountPath: /output
        #docker run --rm -v `pwd`:`pwd` -w `pwd` -i limanling/uiuc_ie_m18 mkdir -p ${PWD}/system/aida_edl
        #docker run -v ${PWD}/system/aida_edl:/data panx27/data-processor wget http://159.89.180.81/demo/resources/edl_data.tar.gz -P /data
        #docker run -v ${PWD}/system/aida_edl:/data panx27/data-processor tar zxvf /data/edl_data.tar.gz -C /data
        #generate rsd
        #docker run --rm -v ${ldc_data}:${ldc_data} -v ${ltf_dir}:${ltf_dir} -i limanling/uiuc_ie_m18 mkdir -p ${ltf_dir}
        #docker run --rm -v ${ldc_data}:${ldc_data} -v ${ltf_dir}:${ltf_dir} -i limanling/uiuc_ie_m18 unzip -o ${ldc_data}/data/ltf/\*.zip -d ${ltf_dir}
        #docker run --rm -v ${ldc_data}:${ldc_data} -v ${ltf_dir}:${ltf_dir} -v ${rsd_dir}:${rsd_dir} -w `pwd` -i limanling/uiuc_ie_m18 perl ${ldc_data}/tools/ltf2txt/ltf2rsd.perl -o ${rsd_dir} ${ltf_dir}        
        - name: setup-edl-rsd         
          image: limanling/uiuc_ie_m18
          command: ["/bin/bash", "-c"]
          args:
           - mkdir -p /output/WORKING/system/aida_edl; 
             wget http://159.89.180.81/demo/resources/edl_data.tar.gz -P /output/WORKING/system/aida_edl; 
             tar zxvf /output/WORKING/system/aida_edl/edl_data.tar.gz -C /output/WORKING/data;
             mkdir -p /output/WORKING/system/rsd;
             perl /input/tools/ltf2txt/ltf2rsd.perl -o /output/WORKING/system/rsd /input/data/ltf;
          volumeMounts:
            - name: input-efs
              mountPath: /input
              readOnly: true
            - name: output-efs
              mountPath: /output #Please put your output here            
      restartPolicy: Never
      nodeSelector:
        eks.amazonaws.com/nodegroup: gaia-eks-nodegroup
---
#docker run -d -i --rm -w /aida_nominal_coreference_en -p 2468:2468 --name nominal_coreference wangqy96/aida_nominal_coreference_en python nominal_backend.py
apiVersion: v1
kind: Pod
metadata:
  name: nominal-coreference
  labels:
    name: nominal-coreference
spec:
  containers:
    - name: nominal-coreference
      image: wangqy96/aida_nominal_coreference_en
      workingDir: /aida_nominal_coreference_en
      command: ["python", "nominal_backend.py"]    
      ports:
      - containerPort: 2468
  nodeSelector:
    eks.amazonaws.com/nodegroup: gaia-eks-nodegroup    
---
#docker run -d -i --rm --name uiuc_ie_m18 -w /entity_api -p 5500:5500 --name aida_entity limanling/uiuc_ie_m18 \
#    /opt/conda/envs/aida_entity/bin/python \
#    /entity_api/entity_api/app.py
apiVersion: v1
kind: Pod
metadata:
  name: aida-entity
  labels:
    name: aida-entity
spec:
  containers:
  - name: aida-entity
    image: limanling/uiuc_ie_m18
    workingDir: /entity_api
    command: ["/opt/conda/envs/aida_entity/bin/python", "/entity_api/entity_api/app.py"]    
    ports:
    - containerPort: 5500
  nodeSelector:
    eks.amazonaws.com/nodegroup: gaia-eks-nodegroup    
---
#docker run -d -i --rm -w /event_coreference_xdoc -p 6001:6001 --name event_coreference_en dylandilu/event_coreference_xdoc python aida_event_coreference_backen_eng.py
apiVersion: v1
kind: Pod
metadata:
  name: event-coreference-en
  labels:
    name: event-coreference-en
spec:
  containers:
  - name: event-coreference-en
    image: dylandilu/event_coreference_xdoc
    workingDir: /event_coreference_xdoc
    command: ["python", "aida_event_coreference_backen_eng.py"]    
    ports:
    - containerPort: 6001
  nodeSelector:
    eks.amazonaws.com/nodegroup: gaia-eks-nodegroup
---
#docker run -d -i --rm -w /event_coreference_xdoc -p 6101:6101 --name event_coreference_ru dylandilu/event_coreference_xdoc python aida_event_coreference_backen_rus.py
apiVersion: v1
kind: Pod
metadata:
  name: event-coreference-ru
  labels:
    name: event-coreference-ru
spec:
  containers:
  - name: event-coreference-ru
    image: dylandilu/event_coreference_xdoc
    workingDir: /event_coreference_xdoc
    command: ["python", "aida_event_coreference_backen_rus.py"]    
    ports:
    - containerPort: 6101
  nodeSelector:
    eks.amazonaws.com/nodegroup: gaia-eks-nodegroup
---
#docker run -d -i --rm -w /event_coreference_xdoc -p 6201:6201 --name event_coreference_uk dylandilu/event_coreference_xdoc python aida_event_coreference_backen_ukr.py
apiVersion: v1
kind: Pod
metadata:
  name: event-coreference-ukr
  labels:
    name: event-coreference-ukr
spec:
  containers:
  - name: event-coreference-ukr
    image: dylandilu/event_coreference_xdoc
    workingDir: /event_coreference_xdoc
    command: ["python", "aida_event_coreference_backen_ukr.py"]    
    ports:
    - containerPort: 6201
  nodeSelector:
    eks.amazonaws.com/nodegroup: gaia-eks-nodegroup    


