apiVersion: batch/v1
kind: Job
metadata:
  name: gaia-ta1
spec:
  template:
    metadata:
      name: gaia-ta1-pipeline
    spec:
      volumes:
        - name: input-efs
          nfs:
            server: fs-36694db5.efs.us-east-1.amazonaws.com #LDC2019E42-efs
            path: /
        - name: output-efs
          nfs:
            server: fs-b7bb8534.efs.us-east-1.amazonaws.com #teamgaia-ta1-output
            path: /
      initContainers:
    #docker run --rm -v ${data_root}:${data_root} -v ${data_root_result}:${data_root_result} -w `pwd` -i limanling/uiuc_ie_m18 \
    #    /opt/conda/envs/py36/bin/python \
    #    /preprocessing/preprocess_detect_languages.py ${data_root_rsd} ${data_root_ltf} ${data_root_result}            
      - name: detect-lang
        image: limanling/uiuc_ie_m18
        command: ["/opt/conda/envs/py36/bin/python"]
        args: ["/preprocessing/preprocess_detect_languages.py /input/data/rsd /input/data/ltf /output/WORKING"]
        volumeMounts:
          - name: input-efs
            mountPath: "/input"
            readOnly: true #Input Volume for worker will be set to readOnly
          - name: output-efs
            mountPath: "/output" #Please put your output here


      #sh preprocess_asr_ocr.sh ${data_root_result} ${asr_en_path} ${ocr_en_path} ${ocr_ru_path}
      
      #extraction
      
      #merging results
      - name: merging-results
        image: limanling/uiuc_ie_m18
        command: ["/opt/conda/envs/py36/bin/python"]
        args: ["/postprocessing/postprocessing_combine_turtle_from_all_sources.py --root_folder /output/WORKING --final_dir_name 'final' output_folder /output/INTER-TA"]
        volumeMounts:
          - name: input-efs
            mountPath: "/input"
            readOnly: true #Input Volume for worker will be set to readOnly
          - name: output-efs
            mountPath: "/output" #Please put your output here

      imagePullSecrets:
        - name: regcred        
      restartPolicy: Never        
      containers:
      - name: finalizer
        image: nextcenturycorp/verdi_finalizer:latest
        args: ["/output", "aida-phase2-ta-performers", "GAIA-TA1-TestRun", "--prefix", "TA1a-GAIA"]
        envFrom:
        - configMapRef:
            name: env-configmap
        - secretRef:
            name: env-secrets
        volumeMounts:
          - name: input-efs
            mountPath: "/input"
          - name: output-efs
            mountPath: "/output"
      imagePullSecrets:
        - name: regcred            
      restartPolicy: Never
      nodeSelector:
        eks.amazonaws.com/nodegroup: gaia-eks-nodegroup

    